'use strict';

const MINIMAP_PANEL_TILES_W = 7;
const MINIMAP_PANEL_TILES_H = 11;
const MINIMAP_TILE_SIZE_PX = 8;
const MINIMAP_PANEL_CELL_COUNT = MINIMAP_PANEL_TILES_W * MINIMAP_PANEL_TILES_H;
const MINIMAP_PANEL_PX_W = MINIMAP_PANEL_TILES_W * MINIMAP_TILE_SIZE_PX;
const MINIMAP_PANEL_PX_H = MINIMAP_PANEL_TILES_H * MINIMAP_TILE_SIZE_PX;
const MINIMAP_TILE_INDEX_MASK = 0x07FF;

module.exports = {
	MINIMAP_PANEL_TILES_W,
	MINIMAP_PANEL_TILES_H,
	MINIMAP_TILE_SIZE_PX,
	MINIMAP_PANEL_CELL_COUNT,
	MINIMAP_PANEL_PX_W,
	MINIMAP_PANEL_PX_H,
	MINIMAP_TILE_INDEX_MASK,
};
