'use strict';

const PREVIEW_START_VERTICALITY_MIN = 0.72;
const PREVIEW_START_MEAN_ABS_TURN_MAX = 0.14;
const PREVIEW_START_MAX_ABS_TURN_MAX = 0.24;
const PREVIEW_TOP_PENALTY_RATIO = 0.28;
const PREVIEW_TOP_PENALTY_SCALE = 2.5;
const PREVIEW_EDGE_LEFT_MIN = 6;
const PREVIEW_EDGE_RIGHT_MARGIN = 7;
const PREVIEW_EDGE_PENALTY = 12;
const PREVIEW_HORIZONTAL_PENALTY_SCALE = 18;
const PREVIEW_SPAN_SCORE_SCALE = 2.5;
const PREVIEW_TURN_SCORE_SCALE = 24;
const PREVIEW_INFLECTION_PENALTY = 18;
const PREVIEW_UNDERDRAWN_USED_CELL_RATIO = 0.72;
const PREVIEW_UNDERDRAWN_USED_CELL_MIN = 18;
const PREVIEW_LOWER_TAIL_START_RATIO = 0.66;
const PREVIEW_LOWER_TAIL_MIN_INDEX_GAP = 6;
const PREVIEW_LOWER_TAIL_EXPAND_FACTOR = 1.18;
const PREVIEW_LOWER_TAIL_EXPAND_START_RATIO = 0.60;
const PREVIEW_COLLAPSE_SEGMENT_MAX = 2.6;
const PREVIEW_COVERAGE_TOLERANCE = 2.5;
const PREVIEW_SIGN_MATCH_MIN = 60;
const PREVIEW_SIGN_MATCH_SLACK = 6;
const PREVIEW_GUIDE_SAMPLE_MIN = 96;
const PREVIEW_GUIDE_BLEND_UNDERDRAWN = [0.25, 0.4];
const PREVIEW_GUIDE_BLEND_NORMAL = [0.12, 0.2];

module.exports = {
	PREVIEW_START_VERTICALITY_MIN,
	PREVIEW_START_MEAN_ABS_TURN_MAX,
	PREVIEW_START_MAX_ABS_TURN_MAX,
	PREVIEW_TOP_PENALTY_RATIO,
	PREVIEW_TOP_PENALTY_SCALE,
	PREVIEW_EDGE_LEFT_MIN,
	PREVIEW_EDGE_RIGHT_MARGIN,
	PREVIEW_EDGE_PENALTY,
	PREVIEW_HORIZONTAL_PENALTY_SCALE,
	PREVIEW_SPAN_SCORE_SCALE,
	PREVIEW_TURN_SCORE_SCALE,
	PREVIEW_INFLECTION_PENALTY,
	PREVIEW_UNDERDRAWN_USED_CELL_RATIO,
	PREVIEW_UNDERDRAWN_USED_CELL_MIN,
	PREVIEW_LOWER_TAIL_START_RATIO,
	PREVIEW_LOWER_TAIL_MIN_INDEX_GAP,
	PREVIEW_LOWER_TAIL_EXPAND_FACTOR,
	PREVIEW_LOWER_TAIL_EXPAND_START_RATIO,
	PREVIEW_COLLAPSE_SEGMENT_MAX,
	PREVIEW_COVERAGE_TOLERANCE,
	PREVIEW_SIGN_MATCH_MIN,
	PREVIEW_SIGN_MATCH_SLACK,
	PREVIEW_GUIDE_SAMPLE_MIN,
	PREVIEW_GUIDE_BLEND_UNDERDRAWN,
	PREVIEW_GUIDE_BLEND_NORMAL,
};
